name: animated_dashed_circle
description: Animated Dashed Circle. If you want to make instagram stories, you can use this package.
version: 0.0.5
homepage: https://github.com/ahmetveysels/
repository: https://github.com/ahmetveysels/animated_dashed_circle/
documentation: https://github.com/ahmetveysels/animated_dashed_circle/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
